/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface AnnotationContainer {
        /**
          * The first name
         */
        "first": string;
        /**
          * The last name
         */
        "last": string;
        /**
          * The middle name
         */
        "middle": string;
    }
    interface AnnotationEditor {
        /**
          * The first name
         */
        "first": string;
        /**
          * The last name
         */
        "last": string;
        /**
          * The middle name
         */
        "middle": string;
    }
    interface EwcAxes {
        "border": number;
        "containerResize": any;
        "for": string;
        "media": string;
    }
    interface EwcAxisX {
        "disabled": boolean;
        "max": number;
        "min": number;
        "step": number;
    }
    interface EwcAxisY {
        "disabled": boolean;
        "max": number;
        "min": number;
        "step": number;
    }
    interface EwcMediaControls {
        "for": string;
    }
    interface GridLinesX {
        /**
          * The first name
         */
        "first": string;
        /**
          * The last name
         */
        "last": string;
        /**
          * The middle name
         */
        "middle": string;
    }
    interface GridLinesY {
        /**
          * The first name
         */
        "first": string;
        /**
          * The last name
         */
        "last": string;
        /**
          * The middle name
         */
        "middle": string;
    }
    interface PositionIndicator {
        /**
          * The first name
         */
        "first": string;
        /**
          * The last name
         */
        "last": string;
        /**
          * The middle name
         */
        "middle": string;
    }
    interface XAnnotate {
        /**
          * The first name
         */
        "first": string;
        /**
          * The last name
         */
        "last": string;
        /**
          * The middle name
         */
        "middle": string;
    }
    interface XAnnotation {
        /**
          * The first name
         */
        "first": string;
        /**
          * The last name
         */
        "last": string;
        /**
          * The middle name
         */
        "middle": string;
    }
    interface XCoords {
        /**
          * The first name
         */
        "first": string;
        /**
          * The last name
         */
        "last": string;
        /**
          * The middle name
         */
        "middle": string;
    }
    interface XSpectrogram {
        /**
          * The first name
         */
        "first": string;
        /**
          * The last name
         */
        "last": string;
        /**
          * The middle name
         */
        "middle": string;
    }
    interface XTag {
        /**
          * The first name
         */
        "first": string;
        /**
          * The last name
         */
        "last": string;
        /**
          * The middle name
         */
        "middle": string;
    }
    interface XTags {
        /**
          * The first name
         */
        "first": string;
        /**
          * The last name
         */
        "last": string;
        /**
          * The middle name
         */
        "middle": string;
    }
}
declare global {
    interface HTMLAnnotationContainerElement extends Components.AnnotationContainer, HTMLStencilElement {
    }
    var HTMLAnnotationContainerElement: {
        prototype: HTMLAnnotationContainerElement;
        new (): HTMLAnnotationContainerElement;
    };
    interface HTMLAnnotationEditorElement extends Components.AnnotationEditor, HTMLStencilElement {
    }
    var HTMLAnnotationEditorElement: {
        prototype: HTMLAnnotationEditorElement;
        new (): HTMLAnnotationEditorElement;
    };
    interface HTMLEwcAxesElement extends Components.EwcAxes, HTMLStencilElement {
    }
    var HTMLEwcAxesElement: {
        prototype: HTMLEwcAxesElement;
        new (): HTMLEwcAxesElement;
    };
    interface HTMLEwcAxisXElement extends Components.EwcAxisX, HTMLStencilElement {
    }
    var HTMLEwcAxisXElement: {
        prototype: HTMLEwcAxisXElement;
        new (): HTMLEwcAxisXElement;
    };
    interface HTMLEwcAxisYElement extends Components.EwcAxisY, HTMLStencilElement {
    }
    var HTMLEwcAxisYElement: {
        prototype: HTMLEwcAxisYElement;
        new (): HTMLEwcAxisYElement;
    };
    interface HTMLEwcMediaControlsElement extends Components.EwcMediaControls, HTMLStencilElement {
    }
    var HTMLEwcMediaControlsElement: {
        prototype: HTMLEwcMediaControlsElement;
        new (): HTMLEwcMediaControlsElement;
    };
    interface HTMLGridLinesXElement extends Components.GridLinesX, HTMLStencilElement {
    }
    var HTMLGridLinesXElement: {
        prototype: HTMLGridLinesXElement;
        new (): HTMLGridLinesXElement;
    };
    interface HTMLGridLinesYElement extends Components.GridLinesY, HTMLStencilElement {
    }
    var HTMLGridLinesYElement: {
        prototype: HTMLGridLinesYElement;
        new (): HTMLGridLinesYElement;
    };
    interface HTMLPositionIndicatorElement extends Components.PositionIndicator, HTMLStencilElement {
    }
    var HTMLPositionIndicatorElement: {
        prototype: HTMLPositionIndicatorElement;
        new (): HTMLPositionIndicatorElement;
    };
    interface HTMLXAnnotateElement extends Components.XAnnotate, HTMLStencilElement {
    }
    var HTMLXAnnotateElement: {
        prototype: HTMLXAnnotateElement;
        new (): HTMLXAnnotateElement;
    };
    interface HTMLXAnnotationElement extends Components.XAnnotation, HTMLStencilElement {
    }
    var HTMLXAnnotationElement: {
        prototype: HTMLXAnnotationElement;
        new (): HTMLXAnnotationElement;
    };
    interface HTMLXCoordsElement extends Components.XCoords, HTMLStencilElement {
    }
    var HTMLXCoordsElement: {
        prototype: HTMLXCoordsElement;
        new (): HTMLXCoordsElement;
    };
    interface HTMLXSpectrogramElement extends Components.XSpectrogram, HTMLStencilElement {
    }
    var HTMLXSpectrogramElement: {
        prototype: HTMLXSpectrogramElement;
        new (): HTMLXSpectrogramElement;
    };
    interface HTMLXTagElement extends Components.XTag, HTMLStencilElement {
    }
    var HTMLXTagElement: {
        prototype: HTMLXTagElement;
        new (): HTMLXTagElement;
    };
    interface HTMLXTagsElement extends Components.XTags, HTMLStencilElement {
    }
    var HTMLXTagsElement: {
        prototype: HTMLXTagsElement;
        new (): HTMLXTagsElement;
    };
    interface HTMLElementTagNameMap {
        "annotation-container": HTMLAnnotationContainerElement;
        "annotation-editor": HTMLAnnotationEditorElement;
        "ewc-axes": HTMLEwcAxesElement;
        "ewc-axis-x": HTMLEwcAxisXElement;
        "ewc-axis-y": HTMLEwcAxisYElement;
        "ewc-media-controls": HTMLEwcMediaControlsElement;
        "grid-lines-x": HTMLGridLinesXElement;
        "grid-lines-y": HTMLGridLinesYElement;
        "position-indicator": HTMLPositionIndicatorElement;
        "x-annotate": HTMLXAnnotateElement;
        "x-annotation": HTMLXAnnotationElement;
        "x-coords": HTMLXCoordsElement;
        "x-spectrogram": HTMLXSpectrogramElement;
        "x-tag": HTMLXTagElement;
        "x-tags": HTMLXTagsElement;
    }
}
declare namespace LocalJSX {
    interface AnnotationContainer {
        /**
          * The first name
         */
        "first"?: string;
        /**
          * The last name
         */
        "last"?: string;
        /**
          * The middle name
         */
        "middle"?: string;
    }
    interface AnnotationEditor {
        /**
          * The first name
         */
        "first"?: string;
        /**
          * The last name
         */
        "last"?: string;
        /**
          * The middle name
         */
        "middle"?: string;
    }
    interface EwcAxes {
        "border"?: number;
        "containerResize"?: any;
        "for"?: string;
        "media"?: string;
    }
    interface EwcAxisX {
        "disabled"?: boolean;
        "max"?: number;
        "min"?: number;
        "step"?: number;
    }
    interface EwcAxisY {
        "disabled"?: boolean;
        "max"?: number;
        "min"?: number;
        "step"?: number;
    }
    interface EwcMediaControls {
        "for"?: string;
    }
    interface GridLinesX {
        /**
          * The first name
         */
        "first"?: string;
        /**
          * The last name
         */
        "last"?: string;
        /**
          * The middle name
         */
        "middle"?: string;
    }
    interface GridLinesY {
        /**
          * The first name
         */
        "first"?: string;
        /**
          * The last name
         */
        "last"?: string;
        /**
          * The middle name
         */
        "middle"?: string;
    }
    interface PositionIndicator {
        /**
          * The first name
         */
        "first"?: string;
        /**
          * The last name
         */
        "last"?: string;
        /**
          * The middle name
         */
        "middle"?: string;
    }
    interface XAnnotate {
        /**
          * The first name
         */
        "first"?: string;
        /**
          * The last name
         */
        "last"?: string;
        /**
          * The middle name
         */
        "middle"?: string;
    }
    interface XAnnotation {
        /**
          * The first name
         */
        "first"?: string;
        /**
          * The last name
         */
        "last"?: string;
        /**
          * The middle name
         */
        "middle"?: string;
    }
    interface XCoords {
        /**
          * The first name
         */
        "first"?: string;
        /**
          * The last name
         */
        "last"?: string;
        /**
          * The middle name
         */
        "middle"?: string;
    }
    interface XSpectrogram {
        /**
          * The first name
         */
        "first"?: string;
        /**
          * The last name
         */
        "last"?: string;
        /**
          * The middle name
         */
        "middle"?: string;
    }
    interface XTag {
        /**
          * The first name
         */
        "first"?: string;
        /**
          * The last name
         */
        "last"?: string;
        /**
          * The middle name
         */
        "middle"?: string;
    }
    interface XTags {
        /**
          * The first name
         */
        "first"?: string;
        /**
          * The last name
         */
        "last"?: string;
        /**
          * The middle name
         */
        "middle"?: string;
    }
    interface IntrinsicElements {
        "annotation-container": AnnotationContainer;
        "annotation-editor": AnnotationEditor;
        "ewc-axes": EwcAxes;
        "ewc-axis-x": EwcAxisX;
        "ewc-axis-y": EwcAxisY;
        "ewc-media-controls": EwcMediaControls;
        "grid-lines-x": GridLinesX;
        "grid-lines-y": GridLinesY;
        "position-indicator": PositionIndicator;
        "x-annotate": XAnnotate;
        "x-annotation": XAnnotation;
        "x-coords": XCoords;
        "x-spectrogram": XSpectrogram;
        "x-tag": XTag;
        "x-tags": XTags;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "annotation-container": LocalJSX.AnnotationContainer & JSXBase.HTMLAttributes<HTMLAnnotationContainerElement>;
            "annotation-editor": LocalJSX.AnnotationEditor & JSXBase.HTMLAttributes<HTMLAnnotationEditorElement>;
            "ewc-axes": LocalJSX.EwcAxes & JSXBase.HTMLAttributes<HTMLEwcAxesElement>;
            "ewc-axis-x": LocalJSX.EwcAxisX & JSXBase.HTMLAttributes<HTMLEwcAxisXElement>;
            "ewc-axis-y": LocalJSX.EwcAxisY & JSXBase.HTMLAttributes<HTMLEwcAxisYElement>;
            "ewc-media-controls": LocalJSX.EwcMediaControls & JSXBase.HTMLAttributes<HTMLEwcMediaControlsElement>;
            "grid-lines-x": LocalJSX.GridLinesX & JSXBase.HTMLAttributes<HTMLGridLinesXElement>;
            "grid-lines-y": LocalJSX.GridLinesY & JSXBase.HTMLAttributes<HTMLGridLinesYElement>;
            "position-indicator": LocalJSX.PositionIndicator & JSXBase.HTMLAttributes<HTMLPositionIndicatorElement>;
            "x-annotate": LocalJSX.XAnnotate & JSXBase.HTMLAttributes<HTMLXAnnotateElement>;
            "x-annotation": LocalJSX.XAnnotation & JSXBase.HTMLAttributes<HTMLXAnnotationElement>;
            "x-coords": LocalJSX.XCoords & JSXBase.HTMLAttributes<HTMLXCoordsElement>;
            "x-spectrogram": LocalJSX.XSpectrogram & JSXBase.HTMLAttributes<HTMLXSpectrogramElement>;
            "x-tag": LocalJSX.XTag & JSXBase.HTMLAttributes<HTMLXTagElement>;
            "x-tags": LocalJSX.XTags & JSXBase.HTMLAttributes<HTMLXTagsElement>;
        }
    }
}
