/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface AnnotationContainer {
        /**
          * The first name
         */
        "first": string;
        /**
          * The last name
         */
        "last": string;
        /**
          * The middle name
         */
        "middle": string;
    }
    interface AnnotationEditor {
        /**
          * The first name
         */
        "first": string;
        /**
          * The last name
         */
        "last": string;
        /**
          * The middle name
         */
        "middle": string;
    }
    interface AxisX {
        /**
          * The first name
         */
        "first": string;
        /**
          * The last name
         */
        "last": string;
        /**
          * The middle name
         */
        "middle": string;
    }
    interface AxisY {
        /**
          * The first name
         */
        "first": string;
        /**
          * The last name
         */
        "last": string;
        /**
          * The middle name
         */
        "middle": string;
    }
    interface GridLinesX {
        /**
          * The first name
         */
        "first": string;
        /**
          * The last name
         */
        "last": string;
        /**
          * The middle name
         */
        "middle": string;
    }
    interface GridLinesY {
        /**
          * The first name
         */
        "first": string;
        /**
          * The last name
         */
        "last": string;
        /**
          * The middle name
         */
        "middle": string;
    }
    interface MediaControls {
        /**
          * The first name
         */
        "first": string;
        /**
          * The last name
         */
        "last": string;
        /**
          * The middle name
         */
        "middle": string;
    }
    interface PositionIndicator {
        /**
          * The first name
         */
        "first": string;
        /**
          * The last name
         */
        "last": string;
        /**
          * The middle name
         */
        "middle": string;
    }
    interface XAnnotate {
        /**
          * The first name
         */
        "first": string;
        /**
          * The last name
         */
        "last": string;
        /**
          * The middle name
         */
        "middle": string;
    }
    interface XAnnotation {
        /**
          * The first name
         */
        "first": string;
        /**
          * The last name
         */
        "last": string;
        /**
          * The middle name
         */
        "middle": string;
    }
    interface XAxes {
        /**
          * The first name
         */
        "first": string;
        /**
          * The last name
         */
        "last": string;
        /**
          * The middle name
         */
        "middle": string;
    }
    interface XCoords {
        /**
          * The first name
         */
        "first": string;
        /**
          * The last name
         */
        "last": string;
        /**
          * The middle name
         */
        "middle": string;
    }
    interface XSpectrogram {
        /**
          * The first name
         */
        "first": string;
        /**
          * The last name
         */
        "last": string;
        /**
          * The middle name
         */
        "middle": string;
    }
    interface XTag {
        /**
          * The first name
         */
        "first": string;
        /**
          * The last name
         */
        "last": string;
        /**
          * The middle name
         */
        "middle": string;
    }
    interface XTags {
        /**
          * The first name
         */
        "first": string;
        /**
          * The last name
         */
        "last": string;
        /**
          * The middle name
         */
        "middle": string;
    }
}
declare global {
    interface HTMLAnnotationContainerElement extends Components.AnnotationContainer, HTMLStencilElement {
    }
    var HTMLAnnotationContainerElement: {
        prototype: HTMLAnnotationContainerElement;
        new (): HTMLAnnotationContainerElement;
    };
    interface HTMLAnnotationEditorElement extends Components.AnnotationEditor, HTMLStencilElement {
    }
    var HTMLAnnotationEditorElement: {
        prototype: HTMLAnnotationEditorElement;
        new (): HTMLAnnotationEditorElement;
    };
    interface HTMLAxisXElement extends Components.AxisX, HTMLStencilElement {
    }
    var HTMLAxisXElement: {
        prototype: HTMLAxisXElement;
        new (): HTMLAxisXElement;
    };
    interface HTMLAxisYElement extends Components.AxisY, HTMLStencilElement {
    }
    var HTMLAxisYElement: {
        prototype: HTMLAxisYElement;
        new (): HTMLAxisYElement;
    };
    interface HTMLGridLinesXElement extends Components.GridLinesX, HTMLStencilElement {
    }
    var HTMLGridLinesXElement: {
        prototype: HTMLGridLinesXElement;
        new (): HTMLGridLinesXElement;
    };
    interface HTMLGridLinesYElement extends Components.GridLinesY, HTMLStencilElement {
    }
    var HTMLGridLinesYElement: {
        prototype: HTMLGridLinesYElement;
        new (): HTMLGridLinesYElement;
    };
    interface HTMLMediaControlsElement extends Components.MediaControls, HTMLStencilElement {
    }
    var HTMLMediaControlsElement: {
        prototype: HTMLMediaControlsElement;
        new (): HTMLMediaControlsElement;
    };
    interface HTMLPositionIndicatorElement extends Components.PositionIndicator, HTMLStencilElement {
    }
    var HTMLPositionIndicatorElement: {
        prototype: HTMLPositionIndicatorElement;
        new (): HTMLPositionIndicatorElement;
    };
    interface HTMLXAnnotateElement extends Components.XAnnotate, HTMLStencilElement {
    }
    var HTMLXAnnotateElement: {
        prototype: HTMLXAnnotateElement;
        new (): HTMLXAnnotateElement;
    };
    interface HTMLXAnnotationElement extends Components.XAnnotation, HTMLStencilElement {
    }
    var HTMLXAnnotationElement: {
        prototype: HTMLXAnnotationElement;
        new (): HTMLXAnnotationElement;
    };
    interface HTMLXAxesElement extends Components.XAxes, HTMLStencilElement {
    }
    var HTMLXAxesElement: {
        prototype: HTMLXAxesElement;
        new (): HTMLXAxesElement;
    };
    interface HTMLXCoordsElement extends Components.XCoords, HTMLStencilElement {
    }
    var HTMLXCoordsElement: {
        prototype: HTMLXCoordsElement;
        new (): HTMLXCoordsElement;
    };
    interface HTMLXSpectrogramElement extends Components.XSpectrogram, HTMLStencilElement {
    }
    var HTMLXSpectrogramElement: {
        prototype: HTMLXSpectrogramElement;
        new (): HTMLXSpectrogramElement;
    };
    interface HTMLXTagElement extends Components.XTag, HTMLStencilElement {
    }
    var HTMLXTagElement: {
        prototype: HTMLXTagElement;
        new (): HTMLXTagElement;
    };
    interface HTMLXTagsElement extends Components.XTags, HTMLStencilElement {
    }
    var HTMLXTagsElement: {
        prototype: HTMLXTagsElement;
        new (): HTMLXTagsElement;
    };
    interface HTMLElementTagNameMap {
        "annotation-container": HTMLAnnotationContainerElement;
        "annotation-editor": HTMLAnnotationEditorElement;
        "axis-x": HTMLAxisXElement;
        "axis-y": HTMLAxisYElement;
        "grid-lines-x": HTMLGridLinesXElement;
        "grid-lines-y": HTMLGridLinesYElement;
        "media-controls": HTMLMediaControlsElement;
        "position-indicator": HTMLPositionIndicatorElement;
        "x-annotate": HTMLXAnnotateElement;
        "x-annotation": HTMLXAnnotationElement;
        "x-axes": HTMLXAxesElement;
        "x-coords": HTMLXCoordsElement;
        "x-spectrogram": HTMLXSpectrogramElement;
        "x-tag": HTMLXTagElement;
        "x-tags": HTMLXTagsElement;
    }
}
declare namespace LocalJSX {
    interface AnnotationContainer {
        /**
          * The first name
         */
        "first"?: string;
        /**
          * The last name
         */
        "last"?: string;
        /**
          * The middle name
         */
        "middle"?: string;
    }
    interface AnnotationEditor {
        /**
          * The first name
         */
        "first"?: string;
        /**
          * The last name
         */
        "last"?: string;
        /**
          * The middle name
         */
        "middle"?: string;
    }
    interface AxisX {
        /**
          * The first name
         */
        "first"?: string;
        /**
          * The last name
         */
        "last"?: string;
        /**
          * The middle name
         */
        "middle"?: string;
    }
    interface AxisY {
        /**
          * The first name
         */
        "first"?: string;
        /**
          * The last name
         */
        "last"?: string;
        /**
          * The middle name
         */
        "middle"?: string;
    }
    interface GridLinesX {
        /**
          * The first name
         */
        "first"?: string;
        /**
          * The last name
         */
        "last"?: string;
        /**
          * The middle name
         */
        "middle"?: string;
    }
    interface GridLinesY {
        /**
          * The first name
         */
        "first"?: string;
        /**
          * The last name
         */
        "last"?: string;
        /**
          * The middle name
         */
        "middle"?: string;
    }
    interface MediaControls {
        /**
          * The first name
         */
        "first"?: string;
        /**
          * The last name
         */
        "last"?: string;
        /**
          * The middle name
         */
        "middle"?: string;
    }
    interface PositionIndicator {
        /**
          * The first name
         */
        "first"?: string;
        /**
          * The last name
         */
        "last"?: string;
        /**
          * The middle name
         */
        "middle"?: string;
    }
    interface XAnnotate {
        /**
          * The first name
         */
        "first"?: string;
        /**
          * The last name
         */
        "last"?: string;
        /**
          * The middle name
         */
        "middle"?: string;
    }
    interface XAnnotation {
        /**
          * The first name
         */
        "first"?: string;
        /**
          * The last name
         */
        "last"?: string;
        /**
          * The middle name
         */
        "middle"?: string;
    }
    interface XAxes {
        /**
          * The first name
         */
        "first"?: string;
        /**
          * The last name
         */
        "last"?: string;
        /**
          * The middle name
         */
        "middle"?: string;
    }
    interface XCoords {
        /**
          * The first name
         */
        "first"?: string;
        /**
          * The last name
         */
        "last"?: string;
        /**
          * The middle name
         */
        "middle"?: string;
    }
    interface XSpectrogram {
        /**
          * The first name
         */
        "first"?: string;
        /**
          * The last name
         */
        "last"?: string;
        /**
          * The middle name
         */
        "middle"?: string;
    }
    interface XTag {
        /**
          * The first name
         */
        "first"?: string;
        /**
          * The last name
         */
        "last"?: string;
        /**
          * The middle name
         */
        "middle"?: string;
    }
    interface XTags {
        /**
          * The first name
         */
        "first"?: string;
        /**
          * The last name
         */
        "last"?: string;
        /**
          * The middle name
         */
        "middle"?: string;
    }
    interface IntrinsicElements {
        "annotation-container": AnnotationContainer;
        "annotation-editor": AnnotationEditor;
        "axis-x": AxisX;
        "axis-y": AxisY;
        "grid-lines-x": GridLinesX;
        "grid-lines-y": GridLinesY;
        "media-controls": MediaControls;
        "position-indicator": PositionIndicator;
        "x-annotate": XAnnotate;
        "x-annotation": XAnnotation;
        "x-axes": XAxes;
        "x-coords": XCoords;
        "x-spectrogram": XSpectrogram;
        "x-tag": XTag;
        "x-tags": XTags;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "annotation-container": LocalJSX.AnnotationContainer & JSXBase.HTMLAttributes<HTMLAnnotationContainerElement>;
            "annotation-editor": LocalJSX.AnnotationEditor & JSXBase.HTMLAttributes<HTMLAnnotationEditorElement>;
            "axis-x": LocalJSX.AxisX & JSXBase.HTMLAttributes<HTMLAxisXElement>;
            "axis-y": LocalJSX.AxisY & JSXBase.HTMLAttributes<HTMLAxisYElement>;
            "grid-lines-x": LocalJSX.GridLinesX & JSXBase.HTMLAttributes<HTMLGridLinesXElement>;
            "grid-lines-y": LocalJSX.GridLinesY & JSXBase.HTMLAttributes<HTMLGridLinesYElement>;
            "media-controls": LocalJSX.MediaControls & JSXBase.HTMLAttributes<HTMLMediaControlsElement>;
            "position-indicator": LocalJSX.PositionIndicator & JSXBase.HTMLAttributes<HTMLPositionIndicatorElement>;
            "x-annotate": LocalJSX.XAnnotate & JSXBase.HTMLAttributes<HTMLXAnnotateElement>;
            "x-annotation": LocalJSX.XAnnotation & JSXBase.HTMLAttributes<HTMLXAnnotationElement>;
            "x-axes": LocalJSX.XAxes & JSXBase.HTMLAttributes<HTMLXAxesElement>;
            "x-coords": LocalJSX.XCoords & JSXBase.HTMLAttributes<HTMLXCoordsElement>;
            "x-spectrogram": LocalJSX.XSpectrogram & JSXBase.HTMLAttributes<HTMLXSpectrogramElement>;
            "x-tag": LocalJSX.XTag & JSXBase.HTMLAttributes<HTMLXTagElement>;
            "x-tags": LocalJSX.XTags & JSXBase.HTMLAttributes<HTMLXTagsElement>;
        }
    }
}
