name: Publish

on:
  workflow_dispatch:
    inputs:
      tag_name:
        description: "The tag name of the release to publish"
        required: true
        type: string
  workflow_call:
    inputs:
      tag_name:
        required: true
        type: string

jobs:
  Publish-Assets:
    name: Publish Assets to NPM and GitHub
    runs-on: ubuntu-latest
    permissions:
      id-token: write # required for OIDC authentication to NPM registry
      contents: write

    steps:
      # publish to NPM for each release created
      - name: Checkout
        uses: nschloe/action-cached-lfs-checkout@v1
        with:
          ref: ${{ github.ref }}

      # Setup .npmrc file to publish to npm
      - uses: actions/setup-node@v6
        with:
          node-version: "20.x"
          registry-url: "https://registry.npmjs.org"
          scope: "@ecoacoustics"

      - name: Install pnpm
        uses: pnpm/action-setup@v3
        with:
          version: 8
          run_install: |
            - recursive: true
            - args: [--frozen-lockfile]

      - name: Publish to NPM
        run: pnpm publish:components
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

      - name: Publish to GitHub Releases
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          set -e
          mkdir -p ./dist
          zip -r ./dist/components.zip ./assets/ ./@types/ ./dist/
          gh release upload ${{ inputs.tag_name }} ./dist/components.zip

  Publish-Documentation:
    uses: ./.github/workflows/docs-publish.yml
    with:
      production: true
    secrets: inherit
